title: The Morphological Tokenization of Esperanto
description: A research project by Gordon Lichtstein and Marco Cognetta investigating the impact of morphological tokenization on the output of English to Esperanto translations using Fairseq
theme: jekyll-theme-cayman
