title: Esperanto Morphological Tokenization
description: A research project by Gordon Lichtstein using Fairseq to investigate the impact of morphological tokenization on the output of English-Esperanto translations
theme: jekyll-theme-cayman
google_analytics: G-XTRMS024V8
