title: Gordon Lichtstein
description: A website for my code, projects, and bio
theme: jekyll-theme-minimal

plugins:
- jekyll-seo-tag
- jekyll-sitemap

# url: "https://generic-account.github.io"

social:
name: Gordon Lichtstein
links:
- https://www.linkedin.com/in/gordon-lichtstein/
- https://github.com/generic-account