title: Esperanto Morphological Tokenization
description: A research project by Gordon Lichtstein and Marco Cognetta investigating the impact of morphological tokenization on the output of English to Esperanto translations using Fairseq
theme: jekyll-theme-cayman
google_analytics: G-XTRMS024V8
